---
title: "What do FEs do the spectrum?"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
pacman::p_load('tidyverse', 'fixest', 'lubridate', 'patchwork')
theme_set(theme_bw())
set.seed(123)
if(Sys.info()['user'] == "tombearpark") {
  dir <- "/Users/tombearpark/Documents/GitHub/fourier_fe/code"
  out <- "/Users/tombearpark/Dropbox/Apps/Overleaf/What do Fixed Effects do to your Data?/images"
}else{
  stop("You need to set your paths up")
}
source(file.path(dir, "0_funcs.R"))
```

# Section 1: How do FEs affect the spectrum?

First, lets simulate a simple time series...

```{r}
beta <- 0.9

dates   <- 
  expand_grid(unit = 1, year = 1990:2010, month = 1:12) %>% 
  mutate(date = make_date(year = year, month = month, day = 1))

df <- gen_ts(dates, "y1")
m  <- feols(df, y1 ~ 1 | year)
df$residuals1 <- m$residuals

df %>% 
  ggplot() + 
  geom_line(aes(x = date, y = y1), alpha = 0.9)
ggsave(paste0(out, "/ts.png"), height = 4, width = 7)
```

Plot the series...

```{r}
df %>% 
  pivot_longer(c(y1, residuals1)) %>% 
  mutate(alpha = ifelse(name == "y1", 0.5, 0.9)) %>%
  ggplot() + 
  geom_line(aes(x = date, y = value, color = name), alpha = 0.9)
ggsave(paste0(out, "/ts_w_resid.png"), height = 4, width = 7)
```

Get the spectrum of the time series. Calculate a FE

```{r}
compare_spectrums <- function(df, ts1, ts2){
  unit <- df$unit
  ss <- spectrum(df[[ts1]], log = "no", plot = FALSE)
  # Get the spectrum of the residuals
  s1 <- spectrum(df[[ts2]], log = "no", plot = FALSE)
  # Organise and plot outputs...
  tibble(freq = ss$freq, y = ss$spec, filtered = s1$spec) %>% 
    pivot_longer(cols = -c(freq))
}

plot_df <- compare_spectrums(df, "y1", "residuals1")

p1 <- ggplot(plot_df) + 
  geom_line(aes(x = freq, y = value, color = name)) 

p2 <- ggplot(plot_df %>% filter(freq < 0.1)) + 
  geom_line(aes(x = freq, y = value, color = name)) + 
  geom_vline(xintercept = 1 / (length(unique(df$year))))
p <- p1 + p2
ggsave(plot = p, filename = paste0(out, "/ts_spec.png"), height = 4, width = 10)
p
```

Clearly, for an individual time series, filtering the data in this way eliminates the low frequency information.

Next, lets expand this to a panel data setting.

```{r}

gen_panel <- function(no_units){
  map_dfr(1:no_units, 
          function(x) 
            expand_grid(year = 1990:2010, month = 1:12) %>% 
              mutate(date = make_date(year = year, month = month, day = 1), 
                     unit = !!as.factor(x)) %>% 
            gen_ts("y")
  )
}

df2 <- gen_panel(5)

ggplot(df2) + geom_line(aes(x = date, y = y, color = unit))

```

```{r}
m2 <- feols(y ~ 1 | year + unit, data = df2)
df2$residuals <- m2$residuals

m3 <- feols(y ~ 1 | year^unit, data = df2)
df2$residuals_full <- m3$residuals


# Get the spectra of each unit 
compare_spectrums_by_unit <- function(df, ts1, ts2){
  map_dfr(unique(df$unit), 
        function(x){
          df %>% filter(unit == !!x) %>% 
            compare_spectrums(ts1, ts2) %>% 
            mutate(unit = !!x)
        })
}

plot_panel <- function(df){
    ggplot(df) + 
      geom_line(aes(x = log(freq), y = log(value), color = name)) + 
      facet_wrap(~unit, scales = "free", nrow = 1)
}
compare_spectrums_by_unit(df2, "y", "residuals") %>% 
  plot_panel()

ggsave(filename = paste0(out, "/panel_fes_tw_spec.png"), height = 3, width = 10)
```

```{r}
compare_spectrums_by_unit(df2, "y", "residuals_full") %>% 
  plot_panel()
ggsave(filename = paste0(out, "/panel_fes_year_unit_spec.png"), height = 3, width = 10)
```

# 

```{r}
df2$time <- as.numeric(df2$date)
m4 <- feols(y ~ 1 | unit[time] +  unit[time^2]+ + year + unit, data = df2)
df2$residuals_full_wtt <- m4$residuals
compare_spectrums_by_unit(df2, "y", "residuals_full_wtt") %>% 
  plot_panel()
ggsave(filename = paste0(out, "/panel_fes_year_unit_spec_w_tt.png"), height = 3, width = 10)
```
